language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=micro

script:
- set -eo pipefail;
  for e in source/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
